server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/afric_banking?replicaSet=rs0
      database: afric_banking
  application:
    name: auth-service

jwt:
  secret: ${JWT_SECRET:aWdvcnBheS1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tbWluLTI1Ni1iaXRzLXJlcXVpcmVk}
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    com.afric: DEBUG
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
